package cmd

import (
	"bufio"
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"os/exec"
	"strconv"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"mcpscope/internal/store"
)

func init() {
	rootCmd.AddCommand(newReplayCmd())
}

func newReplayCmd() *cobra.Command {
	var inputPath string
	var server string
	var transport string
	var workspace string
	var environment string
	var reportPath string
	var failOnError bool
	var maxLatencyMs int64

	cmd := &cobra.Command{
		Use:   "replay [command...]",
		Short: "Replay exported traces against an MCP server",
		RunE: func(cmd *cobra.Command, args []string) error {
			if strings.TrimSpace(inputPath) == "" {
				return fmt.Errorf("--input is required")
			}

			data, err := os.ReadFile(inputPath)
			if err != nil {
				return fmt.Errorf("read replay input: %w", err)
			}

			var traces []store.Trace
			if err := json.Unmarshal(data, &traces); err != nil {
				return fmt.Errorf("decode replay input: %w", err)
			}
			traces = filterReplayTraces(traces, defaultWorkspace(workspace), defaultEnvironment(environment))

			switch normalized, err := validateTransport(transport); {
			case err != nil:
				return err
			case normalized == "http":
				target := strings.TrimSpace(server)
				if target == "" && len(args) > 0 {
					target = args[0]
				}
				report, err := replayHTTP(cmd.Context(), target, traces)
				if err != nil {
					return err
				}
				return finalizeReplay(cmd, report, reportPath, failOnError, maxLatencyMs)
			default:
				command := commandFromInputs(strings.TrimSpace(server), args)
				if len(command) == 0 {
					return fmt.Errorf("provide --server or a command after `--`")
				}
				report, err := replayStdio(cmd.Context(), command, traces)
				if err != nil {
					return err
				}
				return finalizeReplay(cmd, report, reportPath, failOnError, maxLatencyMs)
			}
		},
	}

	cmd.Flags().StringVar(&inputPath, "input", "", "Path to a JSON trace export generated by `mcpscope export`")
	cmd.Flags().StringVar(&server, "server", "", "Target MCP server command or HTTP URL")
	cmd.Flags().StringVar(&transport, "transport", "stdio", "Replay transport: stdio or http")
	cmd.Flags().StringVar(&workspace, "workspace", "default", "Workspace to replay")
	cmd.Flags().StringVar(&environment, "environment", "default", "Environment to replay")
	cmd.Flags().StringVar(&reportPath, "report", "", "Path to write a replay report JSON summary")
	cmd.Flags().BoolVar(&failOnError, "fail-on-error", false, "Fail if any replayed request returns a JSON-RPC error")
	cmd.Flags().Int64Var(&maxLatencyMs, "max-latency-ms", 0, "Fail if any replayed request exceeds this latency. Use 0 to disable")

	return cmd
}

type replayReport struct {
	Workspace     string         `json:"workspace"`
	Environment   string         `json:"environment"`
	Transport     string         `json:"transport"`
	TotalRequests int            `json:"total_requests"`
	SuccessCount  int            `json:"success_count"`
	ErrorCount    int            `json:"error_count"`
	MaxLatencyMs  int64          `json:"max_latency_ms"`
	RecordedAt    time.Time      `json:"recorded_at"`
	Results       []replayResult `json:"results"`
}

type replayResult struct {
	Method      string `json:"method"`
	TraceID     string `json:"trace_id"`
	Workspace   string `json:"workspace"`
	Environment string `json:"environment"`
	LatencyMs   int64  `json:"latency_ms"`
	IsError     bool   `json:"is_error"`
	Error       string `json:"error,omitempty"`
}

func replayHTTP(ctx context.Context, target string, traces []store.Trace) (replayReport, error) {
	if target == "" {
		return replayReport{}, fmt.Errorf("missing replay target URL")
	}

	client := &http.Client{}
	report := newReplayReport("http", traces)
	for i, trace := range traces {
		if trace.Method == "" {
			continue
		}
		started := time.Now()
		payload, err := json.Marshal(map[string]any{
			"jsonrpc": "2.0",
			"id":      i + 1,
			"method":  trace.Method,
			"params":  json.RawMessage(trace.ParamsPayload),
		})
		if err != nil {
			return replayReport{}, err
		}
		req, err := http.NewRequestWithContext(ctx, http.MethodPost, target, bytes.NewReader(payload))
		if err != nil {
			return replayReport{}, err
		}
		req.Header.Set("Content-Type", "application/json")
		resp, err := client.Do(req)
		if err != nil {
			return replayReport{}, err
		}
		body, _ := io.ReadAll(resp.Body)
		resp.Body.Close()
		recordReplayResult(&report, trace, time.Since(started).Milliseconds(), parseReplayResponseError(body))
	}
	return report, nil
}

func replayStdio(ctx context.Context, command []string, traces []store.Trace) (replayReport, error) {
	cmd := exec.CommandContext(ctx, command[0], command[1:]...)
	stdin, err := cmd.StdinPipe()
	if err != nil {
		return replayReport{}, err
	}
	stdout, err := cmd.StdoutPipe()
	if err != nil {
		return replayReport{}, err
	}
	cmd.Stderr = os.Stderr
	if err := cmd.Start(); err != nil {
		return replayReport{}, err
	}

	report := newReplayReport("stdio", traces)
	reader := bufio.NewReader(stdout)
	for i, trace := range traces {
		if trace.Method == "" {
			continue
		}
		started := time.Now()
		payload, err := json.Marshal(map[string]any{
			"jsonrpc": "2.0",
			"id":      i + 1,
			"method":  trace.Method,
			"params":  json.RawMessage(trace.ParamsPayload),
		})
		if err != nil {
			return replayReport{}, err
		}
		if _, err := fmt.Fprintf(stdin, "Content-Length: %d\r\n\r\n", len(payload)); err != nil {
			return replayReport{}, err
		}
		if _, err := stdin.Write(payload); err != nil {
			return replayReport{}, err
		}
		response, err := readReplayFrame(reader)
		if err != nil {
			return replayReport{}, err
		}
		recordReplayResult(&report, trace, time.Since(started).Milliseconds(), parseReplayResponseError(response))
	}

	stdin.Close()
	if err := cmd.Wait(); err != nil {
		return replayReport{}, err
	}
	return report, nil
}

func readReplayFrame(reader *bufio.Reader) ([]byte, error) {
	contentLength := -1
	for {
		line, err := reader.ReadString('\n')
		if err != nil {
			return nil, err
		}
		trimmed := strings.TrimRight(line, "\r\n")
		if trimmed == "" {
			break
		}
		name, value, found := strings.Cut(trimmed, ":")
		if found && strings.EqualFold(strings.TrimSpace(name), "Content-Length") {
			contentLength, err = strconv.Atoi(strings.TrimSpace(value))
			if err != nil {
				return nil, err
			}
		}
	}
	if contentLength < 0 {
		return nil, fmt.Errorf("missing Content-Length header")
	}
	payload := make([]byte, contentLength)
	_, err := io.ReadFull(reader, payload)
	return payload, err
}

func filterReplayTraces(traces []store.Trace, workspace, environment string) []store.Trace {
	filtered := make([]store.Trace, 0, len(traces))
	for _, trace := range traces {
		if workspace != "" && trace.Workspace != "" && trace.Workspace != workspace {
			continue
		}
		if environment != "" && trace.Environment != "" && trace.Environment != environment {
			continue
		}
		filtered = append(filtered, trace)
	}
	return filtered
}

func newReplayReport(transport string, traces []store.Trace) replayReport {
	report := replayReport{
		Transport:  transport,
		RecordedAt: time.Now().UTC(),
	}
	if len(traces) > 0 {
		report.Workspace = traces[0].Workspace
		report.Environment = traces[0].Environment
	}
	return report
}

func recordReplayResult(report *replayReport, trace store.Trace, latencyMs int64, errMsg string) {
	report.TotalRequests++
	if latencyMs > report.MaxLatencyMs {
		report.MaxLatencyMs = latencyMs
	}
	result := replayResult{
		Method:      trace.Method,
		TraceID:     trace.TraceID,
		Workspace:   trace.Workspace,
		Environment: trace.Environment,
		LatencyMs:   latencyMs,
		IsError:     errMsg != "",
		Error:       errMsg,
	}
	if result.IsError {
		report.ErrorCount++
	} else {
		report.SuccessCount++
	}
	report.Results = append(report.Results, result)
}

func parseReplayResponseError(payload []byte) string {
	var response struct {
		Error json.RawMessage `json:"error"`
	}
	if err := json.Unmarshal(payload, &response); err != nil {
		return ""
	}
	if len(response.Error) == 0 || string(response.Error) == "null" {
		return ""
	}
	return string(response.Error)
}

func finalizeReplay(cmd *cobra.Command, report replayReport, reportPath string, failOnError bool, maxLatencyMs int64) error {
	if reportPath != "" {
		encoded, err := json.MarshalIndent(report, "", "  ")
		if err != nil {
			return err
		}
		if err := os.WriteFile(reportPath, append(encoded, '\n'), 0o644); err != nil {
			return err
		}
	}
	if _, err := fmt.Fprintf(cmd.OutOrStdout(), "replayed %d requests: %d ok, %d error, max latency %d ms\n",
		report.TotalRequests, report.SuccessCount, report.ErrorCount, report.MaxLatencyMs); err != nil {
		return err
	}
	if failOnError && report.ErrorCount > 0 {
		return fmt.Errorf("replay observed %d error responses", report.ErrorCount)
	}
	if maxLatencyMs > 0 && report.MaxLatencyMs > maxLatencyMs {
		return fmt.Errorf("replay max latency %d exceeded limit %d", report.MaxLatencyMs, maxLatencyMs)
	}
	return nil
}
